"""Oracle-backed repository for the SML dataset workspace."""

from __future__ import annotations

import json
from pathlib import Path
import re
import sys
from typing import Any

MONOREPO_ROOT = Path(__file__).resolve().parents[3]
SML_DATASET_PACKAGE = MONOREPO_ROOT / "packages" / "sml-dataset"
if str(SML_DATASET_PACKAGE) not in sys.path:
    sys.path.insert(0, str(SML_DATASET_PACKAGE))

from sml_dataset.connectors.oracle import OracleConnector, oracle_connection
from sml_dataset.metadata import build_metadata


_IDENTIFIER = re.compile(r"^[A-Za-z][A-Za-z0-9_$#]*$")


DDL_STATEMENTS = [
    """
    CREATE TABLE SML_DATASOURCE (
        DATASOURCE_ID      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        DATASOURCE_NAME    VARCHAR2(100) NOT NULL,
        SOURCE_TYPE        VARCHAR2(30) DEFAULT 'ORACLE' NOT NULL,
        DB_KIND            VARCHAR2(30) DEFAULT 'ORACLE' NOT NULL,
        HOST               VARCHAR2(255) NOT NULL,
        PORT               NUMBER DEFAULT 1521 NOT NULL,
        SERVICE_NAME       VARCHAR2(255),
        SID                VARCHAR2(255),
        USERNAME           VARCHAR2(128) NOT NULL,
        DEFAULT_SCHEMA     VARCHAR2(128),
        PASSWORD_SECRET    VARCHAR2(255),
        THICK_MODE_YN      CHAR(1) DEFAULT 'N' NOT NULL,
        DESCRIPTION        VARCHAR2(1000),
        CREATED_BY         VARCHAR2(100),
        CREATED_AT         TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
        UPDATED_AT         TIMESTAMP
    )
    """,
    """
    CREATE TABLE SML_DATASET (
        DATASET_ID         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        PROJECT_NAME       VARCHAR2(150),
        DATASET_NAME       VARCHAR2(150) NOT NULL,
        TASK_CATEGORY      VARCHAR2(30),
        TARGET_MODE        VARCHAR2(30),
        TASK_TYPE          VARCHAR2(50) NOT NULL,
        ALGORITHM_NAME     VARCHAR2(100),
        LIBRARY_NAME       VARCHAR2(100),
        DATASOURCE_ID      NUMBER,
        SOURCE_MODE        VARCHAR2(20) NOT NULL,
        SOURCE_SCHEMA      VARCHAR2(128),
        SOURCE_TABLE       VARCHAR2(128),
        SOURCE_QUERY       CLOB,
        STATUS             VARCHAR2(30) DEFAULT 'DRAFT' NOT NULL,
        ROW_COUNT          NUMBER,
        COLUMN_COUNT       NUMBER,
        TARGET_COLUMNS     CLOB,
        FEATURE_COLUMNS    CLOB,
        PK_COLUMNS         CLOB,
        UNUSED_COLUMNS     CLOB,
        SELECTED_TABLE_NAME VARCHAR2(128),
        METADATA_JSON      CLOB,
        CREATED_BY         VARCHAR2(100),
        CREATED_AT         TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
        UPDATED_AT         TIMESTAMP
    )
    """,
    """
    CREATE TABLE SML_DATASET_VERSION (
        VERSION_ID         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        DATASET_ID         NUMBER NOT NULL,
        VERSION_NAME       VARCHAR2(200) NOT NULL,
        ARTIFACT_PATH      VARCHAR2(1000) NOT NULL,
        METADATA_PATH      VARCHAR2(1000),
        VALIDATION_JSON    CLOB,
        CREATED_BY         VARCHAR2(100),
        CREATED_AT         TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
    )
    """,
]


INDEX_STATEMENTS = [
    "CREATE INDEX IX_SML_DATASOURCE_NAME ON SML_DATASOURCE (DATASOURCE_NAME)",
    "CREATE INDEX IX_SML_DATASET_TASK ON SML_DATASET (TASK_TYPE)",
    "CREATE INDEX IX_SML_DATASET_DATASOURCE ON SML_DATASET (DATASOURCE_ID)",
]

DATASET_COLUMN_UPGRADES = [
    ("ALTER TABLE SML_DATASET ADD PROJECT_NAME VARCHAR2(150)", "PROJECT_NAME"),
    ("ALTER TABLE SML_DATASET ADD TASK_CATEGORY VARCHAR2(30)", "TASK_CATEGORY"),
    ("ALTER TABLE SML_DATASET ADD TARGET_MODE VARCHAR2(30)", "TARGET_MODE"),
    ("ALTER TABLE SML_DATASET ADD ALGORITHM_NAME VARCHAR2(100)", "ALGORITHM_NAME"),
    ("ALTER TABLE SML_DATASET ADD LIBRARY_NAME VARCHAR2(100)", "LIBRARY_NAME"),
    ("ALTER TABLE SML_DATASET ADD PK_COLUMNS CLOB", "PK_COLUMNS"),
    ("ALTER TABLE SML_DATASET ADD UNUSED_COLUMNS CLOB", "UNUSED_COLUMNS"),
    ("ALTER TABLE SML_DATASET ADD SELECTED_TABLE_NAME VARCHAR2(128)", "SELECTED_TABLE_NAME"),
]

TASK_SELECTION_MAP = {
    ("classification", "single"): "binary_classification",
    ("regression", "single"): "single_regression",
    ("regression", "multi"): "multi_regression",
}


def initialize_metadata_store(app_connection: dict[str, Any]) -> dict[str, Any]:
    """Create SML metadata tables if they do not exist."""

    created: list[str] = []
    skipped: list[str] = []
    altered: list[str] = []
    with oracle_connection(app_connection) as conn:
        with conn.cursor() as cursor:
            for statement in DDL_STATEMENTS:
                name = _extract_table_name(statement)
                try:
                    cursor.execute(statement)
                    created.append(name)
                except Exception as exc:  # Oracle returns ORA-00955 when object exists.
                    if "ORA-00955" in str(exc):
                        skipped.append(name)
                    else:
                        raise
            for statement in INDEX_STATEMENTS:
                name = statement.split()[2]
                try:
                    cursor.execute(statement)
                    created.append(name)
                except Exception as exc:
                    if "ORA-00955" in str(exc):
                        skipped.append(name)
                    else:
                        raise
            result = _ensure_dataset_columns(cursor)
            altered.extend(result["altered"])
            skipped.extend(result["skipped"])
        conn.commit()
    return {"created": created, "skipped": skipped, "altered": altered}


def _ensure_dataset_columns(cursor: Any) -> dict[str, list[str]]:
    """Apply additive SML_DATASET schema upgrades without dropping user data."""

    altered: list[str] = []
    skipped: list[str] = []
    for column_statement, column_name in DATASET_COLUMN_UPGRADES:
        try:
            cursor.execute(column_statement)
            altered.append(column_name)
        except Exception as exc:
            if "ORA-01430" in str(exc):
                skipped.append(column_name)
            else:
                raise
    return {"altered": altered, "skipped": skipped}


def create_demo_source_data(app_connection: dict[str, Any]) -> dict[str, Any]:
    """Create a small Oracle source table so the dataset flow can run end to end."""

    table_name = "CUSTOMER_TXN_2024Q4"
    with oracle_connection(app_connection) as conn:
        with conn.cursor() as cursor:
            try:
                cursor.execute(
                    """
                    CREATE TABLE CUSTOMER_TXN_2024Q4 (
                        CUSTOMER_ID     NUMBER PRIMARY KEY,
                        AGE             NUMBER,
                        TENURE_MONTHS   NUMBER,
                        MONTHLY_FEE     NUMBER(10, 2),
                        TOTAL_AMOUNT    NUMBER(12, 2),
                        TXN_COUNT       NUMBER,
                        REGION          VARCHAR2(30),
                        PRODUCT_TYPE    VARCHAR2(30),
                        CHURN           NUMBER(1)
                    )
                    """
                )
            except Exception as exc:
                if "ORA-00955" not in str(exc):
                    raise
            cursor.execute("SELECT COUNT(*) FROM CUSTOMER_TXN_2024Q4")
            current_rows = int(cursor.fetchone()[0])
            if current_rows == 0:
                rows = _demo_customer_rows()
                cursor.executemany(
                    """
                    INSERT INTO CUSTOMER_TXN_2024Q4 (
                        CUSTOMER_ID, AGE, TENURE_MONTHS, MONTHLY_FEE, TOTAL_AMOUNT,
                        TXN_COUNT, REGION, PRODUCT_TYPE, CHURN
                    )
                    VALUES (
                        :customer_id, :age, :tenure_months, :monthly_fee, :total_amount,
                        :txn_count, :region, :product_type, :churn
                    )
                    """,
                    rows,
                )
                current_rows = len(rows)
        conn.commit()
    return {"table": table_name, "rows": current_rows}


def register_datasource(app_connection: dict[str, Any], datasource: dict[str, Any]) -> dict[str, Any]:
    """Persist an Oracle datasource connection in SML_DATASOURCE."""

    payload = {
        "datasource_name": datasource["datasource_name"],
        "source_type": "ORACLE",
        "db_kind": datasource.get("db_kind", "ORACLE"),
        "host": datasource["host"],
        "port": int(datasource.get("port", 1521)),
        "service_name": datasource.get("service_name"),
        "sid": datasource.get("sid"),
        "username": datasource["username"],
        "default_schema": datasource.get("schema") or datasource.get("default_schema") or datasource["username"],
        "password_secret": datasource.get("password") or datasource.get("password_secret"),
        "thick_mode_yn": "Y" if datasource.get("thick_mode") else "N",
        "description": datasource.get("description"),
        "created_by": datasource.get("created_by", "demo-user"),
    }
    if not payload["service_name"] and not payload["sid"]:
        raise ValueError("service_name or sid is required.")
    with oracle_connection(app_connection) as conn:
        with conn.cursor() as cursor:
            datasource_id = cursor.var(int)
            cursor.execute(
                """
                INSERT INTO SML_DATASOURCE (
                    DATASOURCE_NAME, SOURCE_TYPE, DB_KIND, HOST, PORT, SERVICE_NAME, SID,
                    USERNAME, DEFAULT_SCHEMA, PASSWORD_SECRET, THICK_MODE_YN, DESCRIPTION, CREATED_BY
                )
                VALUES (
                    :datasource_name, :source_type, :db_kind, :host, :port, :service_name, :sid,
                    :username, :default_schema, :password_secret, :thick_mode_yn, :description, :created_by
                )
                RETURNING DATASOURCE_ID INTO :datasource_id
                """,
                {**payload, "datasource_id": datasource_id},
            )
        conn.commit()
    return {"datasource_id": int(datasource_id.getvalue()[0]), **_public_datasource(payload)}


def list_datasources(app_connection: dict[str, Any]) -> dict[str, Any]:
    """Return registered datasources without exposing stored passwords."""

    with oracle_connection(app_connection) as conn:
        with conn.cursor() as cursor:
            cursor.execute(
                """
                SELECT DATASOURCE_ID, DATASOURCE_NAME, SOURCE_TYPE, DB_KIND, HOST, PORT,
                       SERVICE_NAME, SID, USERNAME, DEFAULT_SCHEMA, THICK_MODE_YN,
                       DESCRIPTION, CREATED_AT
                FROM SML_DATASOURCE
                ORDER BY DATASOURCE_ID DESC
                """
            )
            rows = cursor.fetchall()
    datasources = [
        {
            "datasource_id": row[0],
            "datasource_name": row[1],
            "source_type": row[2],
            "db_kind": row[3],
            "host": row[4],
            "port": row[5],
            "service_name": row[6],
            "sid": row[7],
            "username": row[8],
            "schema": row[9],
            "thick_mode": row[10] == "Y",
            "description": row[11],
            "created_at": str(row[12]),
        }
        for row in rows
    ]
    return {"datasources": datasources}


def list_datasource_tables(app_connection: dict[str, Any], datasource_id: int, schema: str | None = None) -> dict[str, Any]:
    """List source tables using a stored datasource."""

    datasource = _get_datasource_secret(app_connection, datasource_id)
    source_options = _source_options(datasource)
    schema_name = (schema or datasource["schema"]).upper()
    _validate_identifier(schema_name, "schema")
    with oracle_connection(source_options) as conn:
        with conn.cursor() as cursor:
            cursor.execute(
                """
                SELECT table_name, num_rows
                FROM all_tables
                WHERE owner = :owner
                ORDER BY table_name
                """,
                owner=schema_name,
            )
            tables = [{"schema": schema_name, "table": row[0], "estimated_rows": row[1]} for row in cursor.fetchall()]
    return {"datasource_id": datasource_id, "schema": schema_name, "tables": tables}


def create_dataset_from_datasource(app_connection: dict[str, Any], request: dict[str, Any]) -> dict[str, Any]:
    """Load a preview from a stored datasource and persist dataset metadata."""

    task_fields = _normalize_dataset_task_fields(request)
    datasource_id = int(request["datasource_id"])
    source_mode = request.get("source_mode", "TABLE").upper()
    datasource = _get_datasource_secret(app_connection, datasource_id)
    source_options = _source_options(datasource)
    schema = (request.get("source_schema") or datasource["schema"]).upper()
    table = request.get("source_table")
    query = request.get("source_query")
    preview_rows = int(request.get("preview_rows", 1000))

    if source_mode == "TABLE":
        if not table:
            raise ValueError("source_table is required for TABLE mode.")
        connector = OracleConnector(**source_options, schema=schema, table=table, limit=preview_rows)
        source_query = None
        row_count = _count_table(source_options, schema, table)
    elif source_mode == "SQL":
        if not query:
            raise ValueError("source_query is required for SQL mode.")
        limited_query = _limit_query(query, preview_rows)
        connector = OracleConnector(**source_options, query=limited_query)
        source_query = query
        row_count = None
    else:
        raise ValueError("source_mode must be TABLE or SQL.")

    df = connector.load()
    metadata = build_metadata(df, preview_rows=10)
    metadata_json = json.dumps(metadata, ensure_ascii=False, default=str)

    with oracle_connection(app_connection) as conn:
        with conn.cursor() as cursor:
            _ensure_dataset_columns(cursor)
            dataset_id = cursor.var(int)
            cursor.execute(
                """
                INSERT INTO SML_DATASET (
                    PROJECT_NAME, DATASET_NAME, TASK_CATEGORY, TARGET_MODE,
                    TASK_TYPE, ALGORITHM_NAME, LIBRARY_NAME, DATASOURCE_ID,
                    SOURCE_MODE, SOURCE_SCHEMA, SOURCE_TABLE, SOURCE_QUERY, STATUS,
                    ROW_COUNT, COLUMN_COUNT, METADATA_JSON, CREATED_BY
                )
                VALUES (
                    :project_name, :dataset_name, :task_category, :target_mode,
                    :task_type, :algorithm_name, :library_name, :datasource_id,
                    :source_mode, :source_schema, :source_table, :source_query, 'LOADED',
                    :row_count, :column_count, :metadata_json, :created_by
                )
                RETURNING DATASET_ID INTO :dataset_id
                """,
                {
                    "project_name": request.get("project_name"),
                    "dataset_name": request["dataset_name"],
                    "task_category": task_fields["task_category"],
                    "target_mode": task_fields["target_mode"],
                    "task_type": task_fields["task_type"],
                    "algorithm_name": request.get("algorithm_name"),
                    "library_name": request.get("library_name", "scikit-learn"),
                    "datasource_id": datasource_id,
                    "source_mode": source_mode,
                    "source_schema": schema,
                    "source_table": table.upper() if table else None,
                    "source_query": source_query,
                    "row_count": row_count or len(df),
                    "column_count": len(df.columns),
                    "metadata_json": metadata_json,
                    "created_by": request.get("created_by", "demo-user"),
                    "dataset_id": dataset_id,
                },
            )
        conn.commit()

    return {
        "dataset_id": int(dataset_id.getvalue()[0]),
        "project_name": request.get("project_name"),
        "dataset_name": request["dataset_name"],
        "task_category": task_fields["task_category"],
        "target_mode": task_fields["target_mode"],
        "task_type": task_fields["task_type"],
        "algorithm_name": request.get("algorithm_name"),
        "datasource_id": datasource_id,
        "source_schema": schema,
        "source_table": table.upper() if table else None,
        "row_count": row_count or len(df),
        "column_count": len(df.columns),
        "metadata": metadata,
    }


def _normalize_dataset_task_fields(request: dict[str, Any]) -> dict[str, str | None]:
    """Resolve UI task selections into the modeling task stored for downstream runs."""

    category = request.get("task_category")
    target_mode = request.get("target_mode")
    task_type = request.get("task_type")
    if category and target_mode:
        expected = TASK_SELECTION_MAP.get((category, target_mode))
        if not expected:
            raise ValueError(f"Unsupported task selection: {category}/{target_mode}.")
        if task_type and task_type != expected:
            raise ValueError(f"task_type must be '{expected}' for {category}/{target_mode}.")
        task_type = expected
    if not task_type:
        raise ValueError("task_type is required.")
    return {
        "task_category": category,
        "target_mode": target_mode,
        "task_type": task_type,
    }


def list_datasets(app_connection: dict[str, Any]) -> dict[str, Any]:
    """Return dataset cards persisted in Oracle."""

    with oracle_connection(app_connection) as conn:
        with conn.cursor() as cursor:
            _ensure_dataset_columns(cursor)
            cursor.execute(
                """
                SELECT d.DATASET_ID, d.PROJECT_NAME, d.DATASET_NAME,
                       d.TASK_CATEGORY, d.TARGET_MODE, d.TASK_TYPE, d.ALGORITHM_NAME,
                       d.SOURCE_MODE, d.SOURCE_SCHEMA, d.SOURCE_TABLE, d.STATUS,
                       d.ROW_COUNT, d.COLUMN_COUNT, d.CREATED_AT,
                       s.DATASOURCE_NAME, d.DATASOURCE_ID, d.SOURCE_QUERY,
                       d.TARGET_COLUMNS, d.FEATURE_COLUMNS, d.PK_COLUMNS,
                       d.UNUSED_COLUMNS, d.SELECTED_TABLE_NAME, d.METADATA_JSON
                FROM SML_DATASET d
                LEFT JOIN SML_DATASOURCE s ON s.DATASOURCE_ID = d.DATASOURCE_ID
                ORDER BY d.DATASET_ID DESC
                """
            )
            rows = cursor.fetchall()
    return {
        "datasets": [
            {
                "dataset_id": row[0],
                "project_name": row[1],
                "dataset_name": row[2],
                "task_category": row[3],
                "target_mode": row[4],
                "task_type": row[5],
                "algorithm_name": row[6],
                "source_mode": row[7],
                "source_schema": row[8],
                "source_table": row[9],
                "status": row[10],
                "row_count": row[11],
                "column_count": row[12],
                "created_at": str(row[13]),
                "datasource_name": row[14],
                "datasource_id": row[15],
                "source_query": _read_lob(row[16]),
                "target_columns": _read_json_lob(row[17], []),
                "feature_columns": _read_json_lob(row[18], []),
                "pk_columns": _read_json_lob(row[19], []),
                "unused_columns": _read_json_lob(row[20], []),
                "selected_table_name": row[21],
                "metadata": _read_json_lob(row[22], {}),
            }
            for row in rows
        ]
    }


def get_dataset_process_data(
    app_connection: dict[str, Any],
    dataset_id: int,
    preview_rows: int = 200,
) -> dict[str, Any]:
    """Return dataset metadata and a scrollable preview for the process page."""

    dataset = _get_dataset_record(app_connection, dataset_id)
    if not dataset.get("datasource_id"):
        return {"dataset": dataset, "metadata": dataset.get("metadata", {})}

    datasource = _get_datasource_secret(app_connection, int(dataset["datasource_id"]))
    source_options = _source_options(datasource)
    source_mode = str(dataset["source_mode"]).upper()
    if source_mode == "TABLE":
        connector = OracleConnector(
            **source_options,
            schema=dataset["source_schema"],
            table=dataset["source_table"],
            limit=preview_rows,
        )
    elif source_mode == "SQL":
        connector = OracleConnector(**source_options, query=_limit_query(dataset["source_query"], preview_rows))
    else:
        raise ValueError(f"Unsupported source_mode: {source_mode}.")

    df = connector.load()
    metadata = build_metadata(df, preview_rows=preview_rows)
    dataset["metadata"] = metadata
    return {"dataset": dataset, "metadata": metadata}


def save_dataset_selection(app_connection: dict[str, Any], request: dict[str, Any]) -> dict[str, Any]:
    """Persist target, feature, PK, and unused column selections for the next steps."""

    dataset_id = int(request["dataset_id"])
    targets = list(request.get("target_columns") or [])
    pk_columns = list(request.get("pk_columns") or [])
    unused_columns = list(request.get("unused_columns") or [])
    feature_columns = list(request.get("feature_columns") or [])
    dataset = _get_dataset_record(app_connection, dataset_id)
    if not feature_columns:
        metadata = dataset.get("metadata", {})
        all_columns = [column["name"] for column in metadata.get("columns", [])]
        excluded = set(targets + pk_columns + unused_columns)
        feature_columns = [name for name in all_columns if name not in excluded]

    selection_profile = {
        "target_columns": targets,
        "feature_columns": feature_columns,
        "pk_columns": pk_columns,
        "unused_columns": unused_columns,
        "target_profile": request.get("target_profile") or {},
    }
    selected_columns = list(dict.fromkeys(targets + feature_columns))
    if not selected_columns:
        raise ValueError("At least one target or feature column is required.")
    selected_table_name = _materialize_selected_dataset(app_connection, dataset, selected_columns)
    selection_profile["selected_table_name"] = selected_table_name
    metadata_json = dataset.get("metadata", {}) or {}
    metadata_json["selection"] = selection_profile

    with oracle_connection(app_connection) as conn:
        with conn.cursor() as cursor:
            _ensure_dataset_columns(cursor)
            cursor.execute(
                """
                UPDATE SML_DATASET
                SET TARGET_COLUMNS = :target_columns,
                    FEATURE_COLUMNS = :feature_columns,
                    PK_COLUMNS = :pk_columns,
                    UNUSED_COLUMNS = :unused_columns,
                    SELECTED_TABLE_NAME = :selected_table_name,
                    METADATA_JSON = :metadata_json,
                    UPDATED_AT = SYSTIMESTAMP
                WHERE DATASET_ID = :dataset_id
                """,
                {
                    "target_columns": json.dumps(targets, ensure_ascii=False),
                    "feature_columns": json.dumps(feature_columns, ensure_ascii=False),
                    "pk_columns": json.dumps(pk_columns, ensure_ascii=False),
                    "unused_columns": json.dumps(unused_columns, ensure_ascii=False),
                    "selected_table_name": selected_table_name,
                    "metadata_json": json.dumps(metadata_json, ensure_ascii=False, default=str),
                    "dataset_id": dataset_id,
                },
            )
            if cursor.rowcount == 0:
                raise ValueError(f"Dataset {dataset_id} was not found.")
        conn.commit()
    return {"dataset_id": dataset_id, **selection_profile}


def _get_dataset_record(app_connection: dict[str, Any], dataset_id: int) -> dict[str, Any]:
    """Read one SML_DATASET record with JSON/CLOB columns decoded."""

    with oracle_connection(app_connection) as conn:
        with conn.cursor() as cursor:
            _ensure_dataset_columns(cursor)
            cursor.execute(
                """
                SELECT d.DATASET_ID, d.PROJECT_NAME, d.DATASET_NAME,
                       d.TASK_CATEGORY, d.TARGET_MODE, d.TASK_TYPE, d.ALGORITHM_NAME,
                       d.SOURCE_MODE, d.SOURCE_SCHEMA, d.SOURCE_TABLE, d.STATUS,
                       d.ROW_COUNT, d.COLUMN_COUNT, d.CREATED_AT,
                       s.DATASOURCE_NAME, d.DATASOURCE_ID, d.SOURCE_QUERY,
                       d.TARGET_COLUMNS, d.FEATURE_COLUMNS, d.PK_COLUMNS,
                       d.UNUSED_COLUMNS, d.SELECTED_TABLE_NAME, d.METADATA_JSON
                FROM SML_DATASET d
                LEFT JOIN SML_DATASOURCE s ON s.DATASOURCE_ID = d.DATASOURCE_ID
                WHERE d.DATASET_ID = :dataset_id
                """,
                dataset_id=dataset_id,
            )
            row = cursor.fetchone()
    if not row:
        raise ValueError(f"Dataset {dataset_id} was not found.")
    return {
        "dataset_id": row[0],
        "project_name": row[1],
        "dataset_name": row[2],
        "task_category": row[3],
        "target_mode": row[4],
        "task_type": row[5],
        "algorithm_name": row[6],
        "source_mode": row[7],
        "source_schema": row[8],
        "source_table": row[9],
        "status": row[10],
        "row_count": row[11],
        "column_count": row[12],
        "created_at": str(row[13]),
        "datasource_name": row[14],
        "datasource_id": row[15],
        "source_query": _read_lob(row[16]),
        "target_columns": _read_json_lob(row[17], []),
        "feature_columns": _read_json_lob(row[18], []),
        "pk_columns": _read_json_lob(row[19], []),
        "unused_columns": _read_json_lob(row[20], []),
        "selected_table_name": row[21],
        "metadata": _read_json_lob(row[22], {}),
    }


def _materialize_selected_dataset(
    app_connection: dict[str, Any],
    dataset: dict[str, Any],
    selected_columns: list[str],
) -> str:
    """Create a DB table containing only target and active feature columns."""

    dataset_id = int(dataset["dataset_id"])
    table_name = f"SML_DS_{dataset_id}_SELECTED"
    _validate_identifier(table_name, "table")
    for column in selected_columns:
        _validate_identifier(column, "column")
    column_sql = ", ".join(column.upper() for column in selected_columns)
    source_mode = str(dataset.get("source_mode") or "").upper()

    with oracle_connection(app_connection) as conn:
        with conn.cursor() as cursor:
            try:
                cursor.execute(f"DROP TABLE {table_name} PURGE")
            except Exception as exc:
                if "ORA-00942" not in str(exc):
                    raise
            if source_mode == "TABLE":
                schema = str(dataset.get("source_schema") or "").upper()
                table = str(dataset.get("source_table") or "").upper()
                _validate_identifier(schema, "schema")
                _validate_identifier(table, "table")
                cursor.execute(
                    f"CREATE TABLE {table_name} AS SELECT {column_sql} FROM {schema}.{table}"
                )
            elif source_mode == "SQL":
                query = str(dataset.get("source_query") or "").strip().rstrip(";")
                if not query.lower().startswith("select"):
                    raise ValueError("Only SELECT queries can be materialized.")
                cursor.execute(
                    f"CREATE TABLE {table_name} AS SELECT {column_sql} FROM ({query}) src"
                )
            else:
                raise ValueError(f"Unsupported source_mode: {source_mode}.")
        conn.commit()
    return table_name


def _read_lob(value: Any) -> Any:
    """Return a plain Python value from Oracle CLOB-like values."""

    if value is None:
        return None
    if hasattr(value, "read"):
        return value.read()
    return value


def _read_json_lob(value: Any, default: Any) -> Any:
    """Decode JSON stored as CLOB, falling back to a safe default."""

    raw = _read_lob(value)
    if not raw:
        return default
    try:
        return json.loads(raw)
    except json.JSONDecodeError:
        return default


def _get_datasource_secret(app_connection: dict[str, Any], datasource_id: int) -> dict[str, Any]:
    with oracle_connection(app_connection) as conn:
        with conn.cursor() as cursor:
            cursor.execute(
                """
                SELECT DATASOURCE_ID, DATASOURCE_NAME, HOST, PORT, SERVICE_NAME, SID,
                       USERNAME, DEFAULT_SCHEMA, PASSWORD_SECRET, THICK_MODE_YN
                FROM SML_DATASOURCE
                WHERE DATASOURCE_ID = :datasource_id
                """,
                datasource_id=datasource_id,
            )
            row = cursor.fetchone()
    if not row:
        raise ValueError(f"Datasource {datasource_id} was not found.")
    return {
        "datasource_id": row[0],
        "datasource_name": row[1],
        "host": row[2],
        "port": row[3],
        "service_name": row[4],
        "sid": row[5],
        "username": row[6],
        "schema": row[7],
        "password": row[8],
        "thick_mode": row[9] == "Y",
    }


def _source_options(datasource: dict[str, Any]) -> dict[str, Any]:
    return {
        "host": datasource["host"],
        "port": int(datasource["port"]),
        "service_name": datasource.get("service_name"),
        "sid": datasource.get("sid"),
        "username": datasource["username"],
        "password": datasource["password"],
        "schema": datasource["schema"],
        "thick_mode": datasource.get("thick_mode", False),
    }


def _count_table(options: dict[str, Any], schema: str, table: str) -> int:
    _validate_identifier(schema, "schema")
    _validate_identifier(table, "table")
    with oracle_connection(options) as conn:
        with conn.cursor() as cursor:
            cursor.execute(f"SELECT COUNT(*) FROM {schema}.{table.upper()}")
            return int(cursor.fetchone()[0])


def _limit_query(query: str, limit: int) -> str:
    cleaned = query.strip().rstrip(";")
    if not cleaned.lower().startswith("select"):
        raise ValueError("Only SELECT queries are allowed for dataset creation.")
    return f"SELECT * FROM ({cleaned}) WHERE ROWNUM <= {int(limit)}"


def _validate_identifier(value: str, label: str) -> None:
    if not value or not _IDENTIFIER.match(value):
        raise ValueError(f"Invalid Oracle {label} identifier: {value!r}")


def _extract_table_name(statement: str) -> str:
    parts = statement.split()
    return parts[2] if len(parts) >= 3 else "UNKNOWN"


def _public_datasource(payload: dict[str, Any]) -> dict[str, Any]:
    return {
        "datasource_name": payload["datasource_name"],
        "source_type": payload["source_type"],
        "db_kind": payload["db_kind"],
        "host": payload["host"],
        "port": payload["port"],
        "service_name": payload["service_name"],
        "sid": payload["sid"],
        "username": payload["username"],
        "schema": payload["default_schema"],
        "thick_mode": payload["thick_mode_yn"] == "Y",
        "description": payload["description"],
    }


def _demo_customer_rows() -> list[dict[str, Any]]:
    regions = ["SEOUL", "BUSAN", "DAEGU", "INCHEON", "GWANGJU"]
    products = ["BASIC", "PLUS", "PREMIUM"]
    rows = []
    for index in range(1, 121):
        age = 22 + (index * 7) % 45
        tenure = 1 + (index * 5) % 72
        fee = 19000 + ((index * 1370) % 72000)
        txn_count = 1 + (index * 3) % 55
        total = fee * max(1, tenure) + txn_count * 820
        churn = 1 if (tenure < 10 and txn_count < 12) or index % 17 == 0 else 0
        rows.append(
            {
                "customer_id": index,
                "age": age,
                "tenure_months": tenure,
                "monthly_fee": fee,
                "total_amount": total,
                "txn_count": txn_count,
                "region": regions[index % len(regions)],
                "product_type": products[index % len(products)],
                "churn": churn,
            }
        )
    return rows
